const ret = {};

// App specific constants
const events = [
    'OPEN_SPECTRUM_SCAN_DIALOG',
    'CLOSE_SPECTRUM_SCAN_DIALOG',
    'CHANGE_SELECTED_RADIO',
    'CHANGE_DURATION',
    'CHANGE_FREQ_RANGE',
    'SPECTRUM_SCAN_SETTINGS_RESET',
    'CHANGE_SCAN_RANGE_TO_DEFAULT',
    'SET_RADIO_SETTINGS',
    'SET_COLOR_MIN_MAX',
    'SET_RADIO_FREQ_BANDWIDTH_MAP',
    'HANDLE_SOCKET_RES',
    'HANDLE_WATERFALL_RES',
    'HANDLE_IMPORT',
    'SET_ANALYSIS_GRAPH_DATA',
    'REMOVE_SPECTRUM_SCAN_DATA',
    'SET_SPECTRUM_SCAN_RESULT',
    'START_SPECTRUM_SCAN',
    'SPECTRUM_SCAN_END',
    'SPECTRUM_WEBSOCKET_ERROR',
    'CLEAR_SPECTRUM_ERROR',
];
events.forEach((e) => {
    ret[e] = e;
});

export default ret;
