const ret = {};

// App specific constants
const events = [
    'OPEN_NODE_RECOVERY_DIALOG',
    'CLOSE_NODE_RECOVERY_DIALOG',
    'SET_NODE_RECOVERY_SETTINS',
    'SET_NODE_RECOVERY_TYPE',
    'RESET_NODE_RECOVERY_DATA',
    'CLEAR_CURRENT_RECOVERY_DATA',
    'PUSH_SCANNING_RESULT',
    'START_NODE_SCANNING',
    'END_OF_SCANNING',
    'CLEAR_SCANNING_RESULT',
    'START_NODE_RECOVERY',
    'UPDATE_RECOVER_NODE_STATUS',
    'UPDATE_RECOVER_NODE_RESULT',
    'NODE_RECOVERY_CLOSED',
    'NODE_RECOVERY_COMPLETED',
    'NODE_RECOVERY_STOP_RECOVERY',
    'NODE_RECOVERY_CHANGE_SECRET',
    'NODE_RECOVERY_SAVE_RECOVERY',
    'CLEAR_CURRENT_RECOVERY_DATA',
];
events.forEach((e) => {
    ret[e] = e;
});

export default ret;
